version: '3.8'

services:
  askr-app:
    build: .
    container_name: askr-camera-system
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://askr:${POSTGRES_PASSWORD}@host.docker.internal:5432/askr_cameras
      RTSP_BASE_IP: ${RTSP_BASE_IP}
      RTSP_PORT: ${RTSP_PORT}
      RTSP_USER: ${RTSP_USER}
      RTSP_PASS: ${RTSP_PASS}
      JWT_SECRET: ${JWT_SECRET}
      BACKEND_PORT: 8080
      API_ACCESS_KEY: ${API_ACCESS_KEY}
      STREAM_TOKEN_EXPIRY: ${STREAM_TOKEN_EXPIRY:-30m}
      HLS_DIR: /app/output
      RECORDINGS_DIR: /app/recordings
      NODE_ENV: production
      TZ: Europe/Moscow
    volumes:
      - /opt/rtsp-hls/output:/app/output
      - /opt/rtsp-hls/recordings:/app/recordings
    ports:
      - "80:8080"
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
